In [1]:
import pandas as pd

In [ ]:
pd.Series(1,2,3)

In [19]:
di={"Name":["anand","mango","pen","mobile"],
    "Identity":["human","fruit","object","none"]}

df=pd.DataFrame(di)

In [20]:
print(df)

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     none

In [21]:
df.head()

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     none

In [ ]:
type(df["name"])

In [23]:
df

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     none

In [32]:
import pandas as pd

df2 = pd.DataFrame({
    'id': [1, 2, 3, 4,],
    'weight': [55, 62, 48, 70,]
})

print(df2)

   id  weight
0   1      55
1   2      62
2   3      48
3   4      70

In [ ]:
# merge or join 
pd.merge(df,df2, how="left")

In [ ]:
pd.merge(df,df2, how="outer")

In [ ]:
pd.merge(df,df2, how="right")

In [ ]:
pd.merge(df,df2, how="inner")